const KEY="alphaOneV32";
let state=load(),pending=[],currentCategory="全部",currentSort="value",currentSearch="",watchSearch="",currentDetailId=null,selectedMonth=new Date(new Date().getFullYear(),new Date().getMonth(),1);
const $=id=>document.getElementById(id);
const money=n=>new Intl.NumberFormat("zh-TW",{style:"currency",currency:"TWD",maximumFractionDigits:0}).format(Number(n)||0);
const num=n=>new Intl.NumberFormat("zh-TW",{maximumFractionDigits:2}).format(Number(n)||0);
const pct=n=>`${(Number(n)||0).toFixed(2)}%`;
const uid=()=>crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`;
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
function normalize(v){return{stocks:(v.stocks||[]).map(s=>({...s,favorite:!!s.favorite,reason:s.reason||"",risk:s.risk||""})),trades:v.trades||[],history:v.history||[],dividends:v.dividends||[],watchlist:v.watchlist||[],targets:{ETF:40,金融:20,科技:25,傳產:10,其他:5,...(v.targets||{})}}}
function load(){try{const v=JSON.parse(localStorage.getItem(KEY));if(v?.stocks)return normalize(v);for(const k of["alphaOneV31","alphaOneV30","alphaOneV24","alphaOneV23","alphaOneV22","alphaOneV21"]){const o=JSON.parse(localStorage.getItem(k));if(o?.stocks)return normalize(o)}}catch{}return{stocks:[],trades:[],history:[],dividends:[],watchlist:[],targets:{ETF:40,金融:20,科技:25,傳產:10,其他:5}}}
function save(){localStorage.setItem(KEY,JSON.stringify(state));render()}
function cls(v){return v>0?"gain":v<0?"loss":"flat"}
function toast(msg){const t=$("toast");t.textContent=msg;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),1700)}
function alphaScore(s){let v=60+Math.max(-20,Math.min(20,s.roi*.7))+Math.max(-10,Math.min(10,(s.dayChange||0)*2));if(s.favorite)v+=4;if(s.category==="ETF")v+=5;if(s.category==="金融")v+=3;return Math.round(Math.max(0,Math.min(100,v)))}
function calc(s){const totalCost=s.shares*s.cost,value=s.shares*s.price,pnl=value-totalCost,roi=totalCost?pnl/totalCost*100:0;const b={...s,totalCost,value,pnl,roi};return{...b,score:alphaScore(b)}}
function allStocks(){return state.stocks.map(calc)}
function totals(a){const totalCost=a.reduce((x,s)=>x+s.totalCost,0),totalValue=a.reduce((x,s)=>x+s.value,0);return{totalCost,totalValue,pnl:totalValue-totalCost,roi:totalCost?(totalValue-totalCost)/totalCost*100:0}}
function realized(){return state.trades.reduce((a,t)=>a+Number(t.realized||0),0)}
function dividends(){return state.dividends.reduce((a,d)=>a+Number(d.amount||0),0)}
function go(page,title){document.querySelectorAll(".page").forEach(x=>x.classList.toggle("active",x.id===page));document.querySelectorAll(".nav-btn").forEach(x=>x.classList.toggle("active",x.dataset.page===page));$("pageTitle").textContent=title||document.querySelector(`[data-page="${page}"]`)?.dataset.title||"Alpha One";scrollTo({top:0,behavior:"smooth"})}
document.querySelectorAll(".nav-btn").forEach(b=>b.onclick=()=>go(b.dataset.page,b.dataset.title));
document.querySelectorAll("[data-go]").forEach(b=>b.onclick=()=>go(b.dataset.go,document.querySelector(`[data-page="${b.dataset.go}"]`)?.dataset.title));
document.querySelectorAll(".ledger-tab").forEach(b=>b.onclick=()=>{document.querySelectorAll(".ledger-tab").forEach(x=>x.classList.remove("active"));document.querySelectorAll(".ledger-panel").forEach(x=>x.classList.remove("active"));b.classList.add("active");$(b.dataset.ledger).classList.add("active")});
document.querySelectorAll(".detail-tab").forEach(b=>b.onclick=()=>{document.querySelectorAll(".detail-tab").forEach(x=>x.classList.remove("active"));document.querySelectorAll(".detail-tab-panel").forEach(x=>x.classList.remove("active"));b.classList.add("active");$(b.dataset.detailTab).classList.add("active")});

function render(){
  const all=allStocks(),t=totals(all),r=realized(),d=dividends(),grand=t.pnl+r+d;
  $("totalValue").textContent=money(t.totalValue);$("holdingCount").textContent=`${all.length} 檔持股`;
  $("grandPnl").textContent=money(grand);$("grandPnl").className=cls(grand);$("grandRoi").textContent=pct(grand/(t.totalCost||1)*100);$("grandRoi").className=cls(grand);
  $("unrealizedPnl").textContent=money(t.pnl);$("unrealizedPnl").className=cls(t.pnl);$("realizedPnl").textContent=money(r);$("realizedPnl").className=cls(r);$("dividendTotal").textContent=money(d);$("totalCost").textContent=money(t.totalCost);
  renderBrief(all,t);renderAllocation(all,t.totalValue);renderTop(all);renderHistory();renderHoldings(all);renderWatchlist();renderAnalytics(all,t);renderStrategy(all,t);renderMonthly();renderTrades();renderDividends();renderPreview();if(currentDetailId)renderDetail()
}
function renderBrief(all,t){if(!all.length){$("dailyBrief").textContent="尚未建立持股。可直接新增，或把券商截圖交給我整理成批次匯入格式。";return}const top=[...all].sort((a,b)=>b.score-a.score)[0],weak=[...all].sort((a,b)=>a.score-b.score)[0],max=Math.max(...all.map(x=>x.value)),conc=t.totalValue?max/t.totalValue*100:0;$("dailyBrief").innerHTML=`Alpha Score 最高為 ${top.symbol}（${top.score} 分），最低為 ${weak.symbol}（${weak.score} 分）。<br>目前未實現損益 ${money(t.pnl)}，整體報酬率 ${pct(t.roi)}。${conc>45?`<br>最大單一持股占比約 ${conc.toFixed(1)}%，集中度偏高。`:""}`}
function allocationData(all,totalValue){const cats=["ETF","金融","科技","傳產","其他"],colors=["#2f9cff","#7d5cff","#ff315f","#00d28e","#f0b55b"];const sums=cats.map(c=>all.filter(x=>x.category===c).reduce((a,x)=>a+x.value,0));return{cats,colors,sums,totalValue}}
function applyDonut(el,center,legend,all,totalValue){const {cats,colors,sums}=allocationData(all,totalValue);let acc=0,stops=[];sums.forEach((v,i)=>{if(totalValue&&v){const s=acc/totalValue*100;acc+=v;stops.push(`${colors[i]} ${s}% ${acc/totalValue*100}%`)}});$(el).style.background=stops.length?`conic-gradient(${stops.join(",")})`:"#151c26";$(center).textContent=`${all.length} 檔`;$(legend).innerHTML=cats.map((c,i)=>`<div class="legend-row"><span><i class="dot" style="background:${colors[i]}"></i>${c}</span><strong>${totalValue?(sums[i]/totalValue*100).toFixed(1):"0.0"}%</strong></div>`).join("")}
function renderAllocation(all,totalValue){applyDonut("homeDonut","homeDonutCenter","homeAllocationLegend",all,totalValue);applyDonut("allocationDonut","allocationCenter","allocationLegend",all,totalValue)}
function renderTop(all){const list=[...all].sort((a,b)=>b.value-a.value).slice(0,4);$("topHoldings").innerHTML=list.length?list.map(s=>`<div class="ios-row" data-open="${s.id}"><div><strong>${esc(s.symbol)}｜${esc(s.name||"")}</strong><small>${esc(s.category)}</small></div><div><small>市值</small><strong>${money(s.value)}</strong></div><div><small>損益</small><strong class="${cls(s.pnl)}">${money(s.pnl)}</strong></div></div>`).join(""):'<div class="empty">尚無持股</div>';bindOpen()}
function renderHistory(){const h=[...state.history].sort((a,b)=>a.date.localeCompare(b.date)).slice(-12);if(!h.length){$("historyChart").innerHTML='<div class="empty" style="width:100%">尚無資產快照</div>';$("historyStats").innerHTML="";return}const vals=h.map(x=>x.value),min=Math.min(...vals),max=Math.max(...vals),range=Math.max(1,max-min);$("historyChart").innerHTML=h.map(x=>`<div class="spark-col"><div class="spark-bar" style="height:${18+(x.value-min)/range*82}%"></div><div class="spark-label">${x.date.slice(5)}</div></div>`).join("");const first=h[0].value,last=h.at(-1).value,change=last-first;$("historyStats").innerHTML=`<div><span>起始</span><strong>${money(first)}</strong></div><div><span>目前</span><strong>${money(last)}</strong></div><div><span>變化</span><strong class="${cls(change)}">${money(change)}</strong></div>`}
$("snapshotBtn").onclick=()=>{const t=totals(allStocks()),date=new Date().toISOString().slice(0,10);state.history=state.history.filter(x=>x.date!==date);state.history.push({date,value:t.totalValue,cost:t.totalCost,pnl:t.pnl});save();toast("今日資產快照已記錄")};

function renderHoldings(all){let list=all.filter(x=>currentCategory==="全部"||x.category===currentCategory).filter(x=>!currentSearch||x.symbol.toLowerCase().includes(currentSearch)||String(x.name||"").toLowerCase().includes(currentSearch));list=[...list].sort((a,b)=>currentSort==="symbol"?a.symbol.localeCompare(b.symbol,"zh-Hant"):(b[currentSort]||0)-(a[currentSort]||0));$("holdingsList").innerHTML=list.length?list.map(s=>`<article class="holding-card" data-open="${s.id}"><div class="holding-top"><div><div class="stock-symbol">${esc(s.symbol)}</div><div class="stock-name">${esc(s.name||"")}</div><span class="category-pill">${esc(s.category)}</span></div><div class="stock-pnl"><strong class="${cls(s.pnl)}">${money(s.pnl)}</strong><span class="${cls(s.roi)}">${pct(s.roi)}</span></div></div><div class="holding-metrics"><div><span>總股數</span><strong>${num(s.shares)}</strong></div><div><span>均價</span><strong>${num(s.cost)}</strong></div><div><span>現價</span><strong>${num(s.price)}</strong></div><div><span>Alpha</span><strong>${s.score}</strong></div></div><div class="holding-actions"><button class="mini-btn" data-edit="${s.id}">修改</button><button class="mini-btn delete" data-delete="${s.id}">刪除</button></div></article>`).join(""):'<div class="empty">沒有符合條件的持股</div>';bindOpen();document.querySelectorAll("[data-edit]").forEach(b=>b.onclick=e=>{e.stopPropagation();openStock(state.stocks.find(x=>x.id===b.dataset.edit))});document.querySelectorAll("[data-delete]").forEach(b=>b.onclick=e=>{e.stopPropagation();if(confirm("確定刪除？")){state.stocks=state.stocks.filter(x=>x.id!==b.dataset.delete);save()}})}
function renderWatchlist(){const list=state.watchlist.filter(x=>!watchSearch||x.symbol.toLowerCase().includes(watchSearch)||String(x.name||"").toLowerCase().includes(watchSearch));$("watchlist").innerHTML=list.length?list.map(w=>{const distance=w.target?((w.price-w.target)/w.target*100):0;const progress=w.target?Math.max(0,Math.min(100,100-Math.abs(distance))):0;return `<article class="holding-card"><div class="holding-top"><div><div class="stock-symbol">${esc(w.symbol)}</div><div class="stock-name">${esc(w.name||"")}</div><span class="category-pill">${esc(w.category)}</span></div><div class="stock-pnl"><strong>${num(w.price)}</strong><span class="${w.target&&w.price<=w.target?"loss":"flat"}">${w.target?`買點 ${num(w.target)}`:"未設買點"}</span></div></div><div class="watch-target"><strong>${esc(w.reason||"尚未填寫觀察原因")}</strong><div class="progress"><i style="width:${progress}%"></i></div><div class="stock-name">${w.target?`距理想買點 ${Math.abs(distance).toFixed(2)}%`:"請設定理想買點"}</div></div><div class="holding-actions"><button class="mini-btn" data-watch-edit="${w.id}">修改</button><button class="mini-btn delete" data-watch-delete="${w.id}">刪除</button></div></article>`}).join(""):'<div class="empty">尚無自選觀察股票</div>';document.querySelectorAll("[data-watch-edit]").forEach(b=>b.onclick=()=>openWatch(state.watchlist.find(x=>x.id===b.dataset.watchEdit)));document.querySelectorAll("[data-watch-delete]").forEach(b=>b.onclick=()=>{if(confirm("確定刪除自選？")){state.watchlist=state.watchlist.filter(x=>x.id!==b.dataset.watchDelete);save()}})}
function renderAnalytics(all,t){const byValue=[...all].sort((a,b)=>b.value-a.value),byRoi=[...all].sort((a,b)=>b.roi-a.roi);$("concentrationList").innerHTML=byValue.length?byValue.slice(0,6).map((s,i)=>`<div class="rank-row"><div><strong>${i+1}. ${esc(s.symbol)}｜${esc(s.name||"")}</strong><small>市值 ${money(s.value)}</small></div><strong>${t.totalValue?(s.value/t.totalValue*100).toFixed(1):"0.0"}%</strong></div>`).join(""):'<div class="empty">尚無資料</div>';$("performanceList").innerHTML=byRoi.length?byRoi.slice(0,6).map((s,i)=>`<div class="rank-row"><div><strong>${i+1}. ${esc(s.symbol)}｜${esc(s.name||"")}</strong><small>${money(s.pnl)}</small></div><strong class="${cls(s.roi)}">${pct(s.roi)}</strong></div>`).join(""):'<div class="empty">尚無資料</div>';
const risks=[];if(!all.length)risks.push(["warn","尚無持股","請先建立庫存，才能進行風險分析。"]);else{const max=Math.max(...all.map(x=>x.value)),conc=t.totalValue?max/t.totalValue*100:0;risks.push([conc>50?"bad":conc>35?"warn":"good","單一持股集中度",`最大單一持股占比 ${conc.toFixed(1)}%。`]);const leveraged=all.filter(x=>/正2|2X|槓桿/.test(`${x.name} ${x.symbol}`)).reduce((a,x)=>a+x.value,0);const levRate=t.totalValue?leveraged/t.totalValue*100:0;risks.push([levRate>25?"bad":levRate>10?"warn":"good","槓桿部位",`槓桿型商品占比 ${levRate.toFixed(1)}%。`]);const losers=all.filter(x=>x.roi<-15).length;risks.push([losers>=3?"bad":losers?"warn":"good","深度虧損持股",`報酬率低於 -15% 的持股共 ${losers} 檔。`]);const cats=new Set(all.map(x=>x.category));risks.push([cats.size<=2?"warn":"good","類別分散度",`目前分布於 ${cats.size} 個資產類別。`])}$("riskCheck").innerHTML=risks.map(r=>`<div class="risk-row ${r[0]}"><strong>${r[1]}</strong><small>${r[2]}</small></div>`).join("")}


function renderStrategy(all,t){
  const cats=["ETF","金融","科技","傳產","其他"];
  $("targetInputs").innerHTML=cats.map(c=>`<div class="target-box"><label>${c}<input class="target-input" data-target-cat="${c}" type="number" min="0" max="100" step="1" value="${Number(state.targets[c]||0)}"></label></div>`).join("");
  const totalTarget=cats.reduce((a,c)=>a+Number(state.targets[c]||0),0);
  $("targetTotal").innerHTML=`<span>目標比例總和</span><strong class="${Math.abs(totalTarget-100)<.01?"gain":"flat"}">${totalTarget.toFixed(0)}%</strong>`;
  const current={};cats.forEach(c=>current[c]=all.filter(x=>x.category===c).reduce((a,x)=>a+x.value,0));
  const rows=cats.map(c=>{
    const currentPct=t.totalValue?current[c]/t.totalValue*100:0;
    const targetPct=Number(state.targets[c]||0);
    const diffPct=targetPct-currentPct;
    const amount=t.totalValue*diffPct/100;
    return {c,currentPct,targetPct,diffPct,amount};
  });
  const absTotal=rows.reduce((a,r)=>a+Math.abs(r.amount),0)/2;
  $("rebalanceSummary").innerHTML=t.totalValue?`若要回到目前設定的目標比例，估計需要調整約 <strong>${money(absTotal)}</strong>。這是依目前市值估算，不包含稅費與價格變動。`:"尚無持股，無法產生再平衡建議。";
  $("rebalanceList").innerHTML=t.totalValue?rows.map(r=>`<div class="rebalance-row"><div class="rebalance-head"><strong>${r.c}</strong><span>目前 ${r.currentPct.toFixed(1)}%／目標 ${r.targetPct.toFixed(1)}%</span></div><div class="rebalance-track"><i style="width:${Math.min(100,r.currentPct)}%"></i></div><small>差異 ${r.diffPct>=0?"+":""}${r.diffPct.toFixed(1)}%</small><div class="rebalance-action ${r.amount>=0?"loss":"gain"}">${Math.abs(r.amount)<1000?"接近目標":r.amount>0?`建議補足約 ${money(r.amount)}`:`建議降低約 ${money(Math.abs(r.amount))}`}</div></div>`).join(""):'<div class="empty">尚無資料</div>';
}
$("saveTargetsBtn").onclick=()=>{
  document.querySelectorAll("[data-target-cat]").forEach(i=>state.targets[i.dataset.targetCat]=Number(i.value||0));
  save();toast("目標配置已儲存");
};
function monthKey(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}`}
function renderMonthly(){
  const key=monthKey(selectedMonth);
  $("selectedMonthLabel").textContent=`${selectedMonth.getFullYear()} 年 ${selectedMonth.getMonth()+1} 月`;
  const ts=state.trades.filter(t=>String(t.date||"").startsWith(key));
  const ds=state.dividends.filter(d=>String(d.date||"").startsWith(key));
  const buy=ts.filter(t=>t.type==="buy").reduce((a,t)=>a+t.shares*t.price+Number(t.fee||0),0);
  const sell=ts.filter(t=>t.type==="sell").reduce((a,t)=>a+t.shares*t.price-Number(t.fee||0),0);
  const realized=ts.reduce((a,t)=>a+Number(t.realized||0),0);
  const dividend=ds.reduce((a,d)=>a+Number(d.amount||0),0);
  $("monthBuy").textContent=money(buy);$("monthSell").textContent=money(sell);$("monthRealized").textContent=money(realized);$("monthRealized").className=cls(realized);$("monthDividend").textContent=money(dividend);
  const activities=[
    ...ts.map(t=>({date:t.date,title:`${t.type==="buy"?"買進":"賣出"} ${t.symbol}`,text:`${num(t.shares)} 股 × ${num(t.price)}`,amount:t.type==="sell"?Number(t.realized||0):-(t.shares*t.price+Number(t.fee||0)),type:t.type})),
    ...ds.map(d=>({date:d.date,title:`股息 ${d.symbol}`,text:d.note||d.name||"",amount:Number(d.amount||0),type:"dividend"}))
  ].sort((a,b)=>b.date.localeCompare(a.date));
  $("monthlyActivity").innerHTML=activities.length?activities.map(a=>`<article class="timeline-card"><div class="timeline-head"><div><strong>${esc(a.title)}</strong><div class="stock-name">${esc(a.date)}｜${esc(a.text)}</div></div><strong class="${cls(a.amount)}">${money(a.amount)}</strong></div></article>`).join(""):'<div class="empty">這個月沒有交易或股息紀錄</div>';
}
$("prevMonthBtn").onclick=()=>{selectedMonth=new Date(selectedMonth.getFullYear(),selectedMonth.getMonth()-1,1);renderMonthly()};
$("nextMonthBtn").onclick=()=>{selectedMonth=new Date(selectedMonth.getFullYear(),selectedMonth.getMonth()+1,1);renderMonthly()};

function bindOpen(){document.querySelectorAll("[data-open]").forEach(x=>x.onclick=()=>openDetail(x.dataset.open))}
function openDetail(id){currentDetailId=id;document.querySelectorAll(".detail-tab").forEach((x,i)=>x.classList.toggle("active",i===0));document.querySelectorAll(".detail-tab-panel").forEach((x,i)=>x.classList.toggle("active",i===0));renderDetail();$("detailSheet").classList.add("open");document.body.style.overflow="hidden"}
function closeDetail(){$("detailSheet").classList.remove("open");document.body.style.overflow=""}
$("closeDetail").onclick=closeDetail;$("sheetBackdrop").onclick=closeDetail;
function renderDetail(){const s=allStocks().find(x=>x.id===currentDetailId);if(!s)return;$("detailBadge").textContent=s.category==="ETF"?"市":s.category.slice(0,1);$("detailName").textContent=s.name||s.symbol;$("detailSymbol").textContent=s.symbol;$("detailPrice").textContent=num(s.price);$("detailPnl").textContent=money(s.pnl);$("detailPnl").className=cls(s.pnl);$("detailRoi").textContent=pct(s.roi);$("detailRoi").className=cls(s.roi);$("detailCost").textContent=num(s.cost);$("detailShares").textContent=num(s.shares);$("detailTotalCost").textContent=money(s.totalCost);$("detailMarketValue").textContent=money(s.value);$("detailFavorite").textContent=s.favorite?"★":"☆";$("detailScore").textContent=s.score;$("detailScoreBar").style.width=`${s.score}%`;$("detailAdvice").textContent=s.score>=82?"評分偏強，可續抱並觀察合理加碼點。":s.score>=65?"評分中性，先續抱觀察，不追價。":"評分偏弱，應檢查基本面、趨勢與停損條件。";$("detailReason").value=s.reason||"";$("detailRisk").value=s.risk||"";
const ts=state.trades.filter(x=>x.symbol===s.symbol).sort((a,b)=>a.date.localeCompare(b.date));$("detailTradeList").innerHTML=ts.length?`<div class="trade-row header"><span>成交日</span><span>價格</span><span>數量</span><span>損益／備註</span></div>`+ts.map(t=>`<div class="trade-row"><strong>${esc(t.date.replaceAll("-","/"))}</strong><strong>${num(t.price)}</strong><strong>${num(t.shares)}</strong><strong class="${t.type==="sell"?cls(t.realized):"flat"}">${t.type==="sell"?money(t.realized):esc(t.note||"買進")}</strong></div>`).join(""):'<div class="empty">尚無逐筆交易紀錄</div>';
const buys=ts.filter(x=>x.type==="buy"),maxShares=Math.max(1,...buys.map(x=>x.shares));$("costDistribution").innerHTML=buys.length?buys.map(t=>`<div class="cost-row"><strong>${num(t.price)}</strong><div class="cost-track"><div class="cost-bar" style="width:${t.shares/maxShares*100}%"></div></div><span>${num(t.shares)}股</span></div>`).join(""):'<div class="empty">尚無買進資料</div>';
const ds=state.dividends.filter(x=>x.symbol===s.symbol).sort((a,b)=>b.date.localeCompare(a.date));$("detailDividendTotal").textContent=money(ds.reduce((a,x)=>a+x.amount,0));$("detailDividendCount").textContent=ds.length;$("detailDividendList").innerHTML=ds.length?ds.map(d=>`<div class="mini-row"><span>${esc(d.date)}｜${esc(d.note||"股息")}</span><strong>${money(d.amount)}</strong></div>`).join(""):'<div class="empty">尚無股息紀錄</div>'}
$("detailFavorite").onclick=()=>{const s=state.stocks.find(x=>x.id===currentDetailId);if(s){s.favorite=!s.favorite;save()}};
$("saveDetailNotes").onclick=()=>{const s=state.stocks.find(x=>x.id===currentDetailId);if(s){s.reason=$("detailReason").value.trim();s.risk=$("detailRisk").value.trim();save();toast("投資筆記已儲存")}};

function openStock(s=null){$("dialogTitle").textContent=s?"修改持股":"新增持股";$("stockId").value=s?.id||"";$("symbol").value=s?.symbol||"";$("name").value=s?.name||"";$("category").value=s?.category||"ETF";$("shares").value=s?.shares??"";$("cost").value=s?.cost??"";$("price").value=s?.price??0;$("dayChange").value=s?.dayChange??0;$("stockDialog").showModal()}
$("addBtn").onclick=()=>openStock();$("closeStockDialog").onclick=()=>$("stockDialog").close();
$("stockForm").onsubmit=e=>{e.preventDefault();const id=$("stockId").value,old=state.stocks.find(x=>x.id===id),item={id:id||uid(),symbol:$("symbol").value.trim().toUpperCase(),name:$("name").value.trim(),category:$("category").value,shares:Number($("shares").value),cost:Number($("cost").value),price:Number($("price").value||0),dayChange:Number($("dayChange").value||0),favorite:old?.favorite||false,reason:old?.reason||"",risk:old?.risk||""};state.stocks=id?state.stocks.map(x=>x.id===id?item:x):[...state.stocks,item];$("stockDialog").close();save();toast("持股已儲存")};

function openWatch(w=null){$("watchId").value=w?.id||"";$("watchSymbol").value=w?.symbol||"";$("watchName").value=w?.name||"";$("watchCategory").value=w?.category||"ETF";$("watchPrice").value=w?.price??0;$("watchTarget").value=w?.target??0;$("watchReason").value=w?.reason||"";$("watchDialog").showModal()}
$("addWatchBtn").onclick=()=>openWatch();$("closeWatchDialog").onclick=()=>$("watchDialog").close();
$("watchForm").onsubmit=e=>{e.preventDefault();const id=$("watchId").value,item={id:id||uid(),symbol:$("watchSymbol").value.trim().toUpperCase(),name:$("watchName").value.trim(),category:$("watchCategory").value,price:Number($("watchPrice").value||0),target:Number($("watchTarget").value||0),reason:$("watchReason").value.trim()};state.watchlist=id?state.watchlist.map(x=>x.id===id?item:x):[...state.watchlist,item];$("watchDialog").close();save();toast("自選已儲存")};

function openTrade(prefill=false){$("tradeForm").reset();$("tradeDate").value=new Date().toISOString().slice(0,10);$("tradeFee").value=0;if(prefill&&currentDetailId){const s=state.stocks.find(x=>x.id===currentDetailId);$("tradeSymbol").value=s.symbol;$("tradeName").value=s.name;$("tradeCategory").value=s.category}$("tradeDialog").showModal()}
$("addTradeBtn").onclick=()=>openTrade(false);$("detailAddTrade").onclick=()=>openTrade(true);$("closeTradeDialog").onclick=()=>$("tradeDialog").close();
$("tradeForm").onsubmit=e=>{e.preventDefault();const t={id:uid(),date:$("tradeDate").value,symbol:$("tradeSymbol").value.trim().toUpperCase(),name:$("tradeName").value.trim(),category:$("tradeCategory").value,type:$("tradeType").value,shares:Number($("tradeShares").value),price:Number($("tradePrice").value),fee:Number($("tradeFee").value||0),note:$("tradeNote").value.trim(),realized:0};let h=state.stocks.find(x=>x.symbol===t.symbol);if(t.type==="buy"){if(!h){h={id:uid(),symbol:t.symbol,name:t.name,category:t.category,shares:0,cost:0,price:t.price,dayChange:0,favorite:false,reason:"",risk:""};state.stocks.push(h)}const old=h.shares*h.cost,newc=t.shares*t.price+t.fee;h.cost=(old+newc)/(h.shares+t.shares);h.shares+=t.shares;h.price=t.price}else{if(!h||h.shares<t.shares){toast("持股不足");return}t.realized=(t.price-h.cost)*t.shares-t.fee;h.shares-=t.shares;h.price=t.price;if(h.shares===0)state.stocks=state.stocks.filter(x=>x.id!==h.id)}state.trades.push(t);$("tradeDialog").close();save();toast("交易已儲存")};

function openDividend(prefill=false){$("dividendForm").reset();$("dividendDate").value=new Date().toISOString().slice(0,10);if(prefill&&currentDetailId){const s=state.stocks.find(x=>x.id===currentDetailId);$("dividendSymbol").value=s.symbol;$("dividendName").value=s.name}$("dividendDialog").showModal()}
$("addDividendBtn").onclick=()=>openDividend(false);$("detailAddDividend").onclick=()=>openDividend(true);$("closeDividendDialog").onclick=()=>$("dividendDialog").close();
$("dividendForm").onsubmit=e=>{e.preventDefault();state.dividends.push({id:uid(),date:$("dividendDate").value,symbol:$("dividendSymbol").value.trim().toUpperCase(),name:$("dividendName").value.trim(),amount:Number($("dividendAmount").value),note:$("dividendNote").value.trim()});$("dividendDialog").close();save();toast("股息已儲存")};

function renderTrades(){const list=[...state.trades].sort((a,b)=>b.date.localeCompare(a.date));$("tradeList").innerHTML=list.length?list.map(t=>`<article class="timeline-card"><div class="timeline-head"><div><strong>${esc(t.symbol)}｜${esc(t.name||"")}</strong><div class="stock-name">${t.type==="buy"?"買進":"賣出"}｜${esc(t.date)}</div></div><strong class="${t.type==="sell"?cls(t.realized):""}">${t.type==="sell"?money(t.realized):money(t.shares*t.price+t.fee)}</strong></div><div class="timeline-meta"><div><span>股數</span><strong>${num(t.shares)}</strong></div><div><span>價格</span><strong>${num(t.price)}</strong></div><div><span>手續費</span><strong>${money(t.fee)}</strong></div><div><span>備註</span><strong>${esc(t.note||"—")}</strong></div></div></article>`).join(""):'<div class="empty">尚無交易紀錄</div>'}
function renderDividends(){const list=[...state.dividends].sort((a,b)=>b.date.localeCompare(a.date));$("dividendList").innerHTML=list.length?list.map(d=>`<article class="timeline-card"><div class="timeline-head"><div><strong>${esc(d.symbol)}｜${esc(d.name||"")}</strong><div class="stock-name">${esc(d.date)}｜${esc(d.note||"股息")}</div></div><strong>${money(d.amount)}</strong></div></article>`).join(""):'<div class="empty">尚無股息紀錄</div>'}

$("analyzeImportBtn").onclick=()=>{pending=$("bulkText").value.split(/\r?\n/).map(x=>x.trim()).filter(Boolean).map(line=>{const c=line.split(/\t|,/).map(x=>x.trim());return{symbol:(c[0]||"").toUpperCase(),name:c[1]||"",category:c[2]||"其他",shares:Number(c[3]),cost:Number(c[4]),price:Number(c[5]||0),dayChange:Number(c[6]||0)}});renderPreview();toast(`已分析 ${pending.length} 筆`)};
function renderPreview(){$("importPreview").innerHTML=pending.length?pending.map(x=>`<div class="preview-item"><strong>${esc(x.symbol)}｜${esc(x.name)}</strong><div class="stock-name">${esc(x.category)}｜${num(x.shares)} 股｜均價 ${num(x.cost)}｜現價 ${num(x.price)}</div></div>`).join(""):'<div class="empty">尚無預覽資料</div>'}
$("approveImportBtn").onclick=()=>{for(const x of pending){if(!x.symbol||!Number.isFinite(x.shares)||!Number.isFinite(x.cost))continue;const old=state.stocks.find(s=>s.symbol===x.symbol),item={id:old?.id||uid(),...x,favorite:old?.favorite||false,reason:old?.reason||"",risk:old?.risk||""};if(old)Object.assign(old,item);else state.stocks.push(item)}pending=[];$("bulkText").value="";save();toast("匯入完成")};

document.querySelectorAll(".segment[data-category]").forEach(c=>c.onclick=()=>{document.querySelectorAll(".segment[data-category]").forEach(x=>x.classList.remove("active"));c.classList.add("active");currentCategory=c.dataset.category;render()});
$("searchInput").oninput=e=>{currentSearch=e.target.value.trim().toLowerCase();render()};$("sortSelect").onchange=e=>{currentSort=e.target.value;render()};$("watchSearch").oninput=e=>{watchSearch=e.target.value.trim().toLowerCase();renderWatchlist()};
$("refreshBtn").onclick=async()=>{if(!state.stocks.length&&!state.watchlist.length){toast("目前沒有持股或自選");return}const b=$("refreshBtn");b.disabled=true;b.textContent="…";let ok=0;for(const s of [...state.stocks,...state.watchlist]){for(const m of["tse","otc"]){try{const r=await fetch(`https://mis.twse.com.tw/stock/api/getStockInfo.jsp?ex_ch=${m}_${s.symbol}.tw`,{cache:"no-store"});const j=await r.json(),row=j?.msgArray?.[0];if(row){const p=Number(row.z||row.y);if(p>0){s.price=p;s.name=s.name||row.n;ok++;break}}}catch{}}}save();b.disabled=false;b.textContent="↻";toast(`已更新 ${ok} 檔`)};

function download(content,name,type){const a=document.createElement("a"),blob=new Blob(["\ufeff"+content],{type});a.href=URL.createObjectURL(blob);a.download=name;a.click();URL.revokeObjectURL(a.href)}
$("exportBtn").onclick=()=>download(JSON.stringify({version:"3.2",...state,exportedAt:new Date().toISOString()},null,2),`alpha-one-${new Date().toISOString().slice(0,10)}.json`,"application/json");
$("exportCsvBtn").onclick=()=>download(["股票代號,股票名稱,分類,股數,平均成本,目前價格,今日漲跌幅",...state.stocks.map(s=>[s.symbol,s.name,s.category,s.shares,s.cost,s.price,s.dayChange].join(","))].join("\n"),"alpha-one-holdings.csv","text/csv");
$("importBtn").onclick=()=>$("importFile").click();$("importFile").onchange=async e=>{try{state=normalize(JSON.parse(await e.target.files[0].text()));save();toast("匯入完成")}catch{toast("備份格式錯誤")}e.target.value=""};
$("sampleBtn").onclick=()=>{state={stocks:[{id:uid(),symbol:"00400A",name:"主動國泰動能高息",category:"ETF",shares:3000,cost:13.50,price:13.41,dayChange:-.59,favorite:true,reason:"作為主動式高股息 ETF 部位，分批建立。",risk:"跌破 12.8 或策略失效時重新評估。"},{id:uid(),symbol:"0050",name:"元大台灣50",category:"ETF",shares:2000,cost:174.6,price:188.2,dayChange:1.15,favorite:true,reason:"核心市場部位",risk:"高檔避免追價"},{id:uid(),symbol:"2882",name:"國泰金",category:"金融",shares:5000,cost:54.8,price:61.2,dayChange:-.49,favorite:false,reason:"金融股配置",risk:"留意利率與景氣"}],trades:[{id:uid(),date:"2026-05-14",symbol:"00400A",name:"主動國泰動能高息",category:"ETF",type:"buy",shares:1000,price:13.91,fee:0,note:"首次建立部位",realized:0},{id:uid(),date:"2026-05-15",symbol:"00400A",name:"主動國泰動能高息",category:"ETF",type:"buy",shares:1000,price:13.50,fee:0,note:"第二次加碼",realized:0},{id:uid(),date:"2026-05-19",symbol:"00400A",name:"主動國泰動能高息",category:"ETF",type:"buy",shares:500,price:12.78,fee:0,note:"逢低加碼",realized:0},{id:uid(),date:"2026-07-17",symbol:"00400A",name:"主動國泰動能高息",category:"ETF",type:"buy",shares:500,price:13.31,fee:0,note:"分批加碼",realized:0}],history:[],dividends:[],targets:{ETF:45,金融:20,科技:25,傳產:5,其他:5},watchlist:[{id:uid(),symbol:"2330",name:"台積電",category:"科技",price:1180,target:1100,reason:"等待拉回再分批建立"},{id:uid(),symbol:"2881",name:"富邦金",category:"金融",price:92.5,target:88,reason:"觀察金融股回檔買點"}]};save();toast("示範資料已載入")};
$("clearBtn").onclick=()=>{if(confirm("確定清空全部資料？")){state={stocks:[],trades:[],history:[],dividends:[],watchlist:[],targets:{ETF:40,金融:20,科技:25,傳產:10,其他:5}};save()}};
render();