const KEY="alphaOneV30";
let state=load(),pending=[],currentCategory="全部",currentSort="value",currentSearch="",currentDetailId=null;
const $=id=>document.getElementById(id);
const money=n=>new Intl.NumberFormat("zh-TW",{style:"currency",currency:"TWD",maximumFractionDigits:0}).format(Number(n)||0);
const num=n=>new Intl.NumberFormat("zh-TW",{maximumFractionDigits:2}).format(Number(n)||0);
const pct=n=>`${(Number(n)||0).toFixed(2)}%`;
const uid=()=>crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`;
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
function normalize(v){return{stocks:(v.stocks||[]).map(s=>({...s,favorite:!!s.favorite,reason:s.reason||"",risk:s.risk||""})),trades:v.trades||[],history:v.history||[],dividends:v.dividends||[]}}
function load(){try{const v=JSON.parse(localStorage.getItem(KEY));if(v?.stocks)return normalize(v);for(const k of["alphaOneV24","alphaOneV23","alphaOneV22","alphaOneV21"]){const o=JSON.parse(localStorage.getItem(k));if(o?.stocks)return normalize(o)}}catch{}return{stocks:[],trades:[],history:[],dividends:[]}}
function save(){localStorage.setItem(KEY,JSON.stringify(state));render()}
function cls(v){return v>0?"gain":v<0?"loss":"flat"}
function toast(msg){const t=$("toast");t.textContent=msg;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),1700)}
function alphaScore(s){let v=60+Math.max(-20,Math.min(20,s.roi*.7))+Math.max(-10,Math.min(10,(s.dayChange||0)*2));if(s.favorite)v+=4;if(s.category==="ETF")v+=5;if(s.category==="金融")v+=3;return Math.round(Math.max(0,Math.min(100,v)))}
function calc(s){const totalCost=s.shares*s.cost,value=s.shares*s.price,pnl=value-totalCost,roi=totalCost?pnl/totalCost*100:0;const b={...s,totalCost,value,pnl,roi};return{...b,score:alphaScore(b)}}
function allStocks(){return state.stocks.map(calc)}
function totals(a){const totalCost=a.reduce((x,s)=>x+s.totalCost,0),totalValue=a.reduce((x,s)=>x+s.value,0);return{totalCost,totalValue,pnl:totalValue-totalCost,roi:totalCost?(totalValue-totalCost)/totalCost*100:0}}
function realized(){return state.trades.reduce((a,t)=>a+Number(t.realized||0),0)}
function dividends(){return state.dividends.reduce((a,d)=>a+Number(d.amount||0),0)}
function go(page,title){document.querySelectorAll(".page").forEach(x=>x.classList.toggle("active",x.id===page));document.querySelectorAll(".nav-btn").forEach(x=>x.classList.toggle("active",x.dataset.page===page));$("pageTitle").textContent=title||document.querySelector(`[data-page="${page}"]`)?.dataset.title||"Alpha One";scrollTo({top:0,behavior:"smooth"})}
document.querySelectorAll(".nav-btn").forEach(b=>b.onclick=()=>go(b.dataset.page,b.dataset.title));
document.querySelectorAll("[data-go]").forEach(b=>b.onclick=()=>go(b.dataset.go,"我的持股"));
document.querySelectorAll(".ledger-tab").forEach(b=>b.onclick=()=>{document.querySelectorAll(".ledger-tab").forEach(x=>x.classList.remove("active"));document.querySelectorAll(".ledger-panel").forEach(x=>x.classList.remove("active"));b.classList.add("active");$(b.dataset.ledger).classList.add("active")});

function render(){
  const all=allStocks(),t=totals(all),r=realized(),d=dividends(),grand=t.pnl+r+d;
  $("totalValue").textContent=money(t.totalValue);$("holdingCount").textContent=`${all.length} 檔持股`;
  $("grandPnl").textContent=money(grand);$("grandPnl").className=cls(grand);$("grandRoi").textContent=pct(grand/(t.totalCost||1)*100);$("grandRoi").className=cls(grand);
  $("unrealizedPnl").textContent=money(t.pnl);$("unrealizedPnl").className=cls(t.pnl);$("realizedPnl").textContent=money(r);$("realizedPnl").className=cls(r);$("dividendTotal").textContent=money(d);$("totalCost").textContent=money(t.totalCost);
  renderBrief(all,t);renderTop(all);renderHistory();renderHoldings(all);renderTrades();renderDividends();renderPreview();if(currentDetailId)renderDetail()
}
function renderBrief(all,t){if(!all.length){$("dailyBrief").textContent="尚未建立持股。可直接新增，或把券商截圖交給我整理成批次匯入格式。";return}const top=[...all].sort((a,b)=>b.score-a.score)[0],weak=[...all].sort((a,b)=>a.score-b.score)[0],max=Math.max(...all.map(x=>x.value)),conc=t.totalValue?max/t.totalValue*100:0;$("dailyBrief").innerHTML=`Alpha Score 最高為 ${top.symbol}（${top.score} 分），最低為 ${weak.symbol}（${weak.score} 分）。<br>目前未實現損益 ${money(t.pnl)}，整體報酬率 ${pct(t.roi)}。${conc>45?`<br>最大單一持股占比約 ${conc.toFixed(1)}%，集中度偏高。`:""}`}
function renderTop(all){const list=[...all].sort((a,b)=>b.value-a.value).slice(0,4);$("topHoldings").innerHTML=list.length?list.map(s=>`<div class="ios-row" data-open="${s.id}"><div><strong>${esc(s.symbol)}｜${esc(s.name||"")}</strong><small>${esc(s.category)}</small></div><div><small>市值</small><strong>${money(s.value)}</strong></div><div><small>損益</small><strong class="${cls(s.pnl)}">${money(s.pnl)}</strong></div></div>`).join(""):'<div class="empty">尚無持股</div>';bindOpen()}
function renderHistory(){const h=[...state.history].sort((a,b)=>a.date.localeCompare(b.date)).slice(-12);if(!h.length){$("historyChart").innerHTML='<div class="empty" style="width:100%">尚無資產快照</div>';$("historyStats").innerHTML="";return}const vals=h.map(x=>x.value),min=Math.min(...vals),max=Math.max(...vals),range=Math.max(1,max-min);$("historyChart").innerHTML=h.map(x=>`<div class="spark-col"><div class="spark-bar" style="height:${18+(x.value-min)/range*82}%"></div><div class="spark-label">${x.date.slice(5)}</div></div>`).join("");const first=h[0].value,last=h.at(-1).value,change=last-first;$("historyStats").innerHTML=`<div><span>起始</span><strong>${money(first)}</strong></div><div><span>目前</span><strong>${money(last)}</strong></div><div><span>變化</span><strong class="${cls(change)}">${money(change)}</strong></div>`}
$("snapshotBtn").onclick=()=>{const t=totals(allStocks()),date=new Date().toISOString().slice(0,10);state.history=state.history.filter(x=>x.date!==date);state.history.push({date,value:t.totalValue,cost:t.totalCost,pnl:t.pnl});save();toast("今日資產快照已記錄")};

function renderHoldings(all){let list=all.filter(x=>currentCategory==="全部"||x.category===currentCategory).filter(x=>!currentSearch||x.symbol.toLowerCase().includes(currentSearch)||String(x.name||"").toLowerCase().includes(currentSearch));list=[...list].sort((a,b)=>currentSort==="symbol"?a.symbol.localeCompare(b.symbol,"zh-Hant"):(b[currentSort]||0)-(a[currentSort]||0));$("holdingsList").innerHTML=list.length?list.map(s=>`<article class="holding-card" data-open="${s.id}"><div class="holding-top"><div><div class="stock-symbol">${esc(s.symbol)}</div><div class="stock-name">${esc(s.name||"")}</div><span class="category-pill">${esc(s.category)}</span></div><div class="stock-pnl"><strong class="${cls(s.pnl)}">${money(s.pnl)}</strong><span class="${cls(s.roi)}">${pct(s.roi)}</span></div></div><div class="holding-metrics"><div><span>總股數</span><strong>${num(s.shares)}</strong></div><div><span>均價</span><strong>${num(s.cost)}</strong></div><div><span>現價</span><strong>${num(s.price)}</strong></div><div><span>Alpha</span><strong>${s.score}</strong></div></div><div class="holding-actions"><button class="mini-btn" data-edit="${s.id}">修改</button><button class="mini-btn delete" data-delete="${s.id}">刪除</button></div></article>`).join(""):'<div class="empty">沒有符合條件的持股</div>';bindOpen();document.querySelectorAll("[data-edit]").forEach(b=>b.onclick=e=>{e.stopPropagation();openStock(state.stocks.find(x=>x.id===b.dataset.edit))});document.querySelectorAll("[data-delete]").forEach(b=>b.onclick=e=>{e.stopPropagation();if(confirm("確定刪除？")){state.stocks=state.stocks.filter(x=>x.id!==b.dataset.delete);save()}})}
function bindOpen(){document.querySelectorAll("[data-open]").forEach(x=>x.onclick=()=>openDetail(x.dataset.open))}
function openDetail(id){currentDetailId=id;renderDetail();$("detailSheet").classList.add("open");document.body.style.overflow="hidden"}
function closeDetail(){$("detailSheet").classList.remove("open");document.body.style.overflow=""}
$("closeDetail").onclick=closeDetail;$("sheetBackdrop").onclick=closeDetail;
function renderDetail(){const s=allStocks().find(x=>x.id===currentDetailId);if(!s)return;$("detailBadge").textContent=s.category==="ETF"?"市":s.category.slice(0,1);$("detailName").textContent=s.name||s.symbol;$("detailSymbol").textContent=s.symbol;$("detailPrice").textContent=num(s.price);$("detailPnl").textContent=money(s.pnl);$("detailPnl").className=cls(s.pnl);$("detailRoi").textContent=pct(s.roi);$("detailRoi").className=cls(s.roi);$("detailCost").textContent=num(s.cost);$("detailShares").textContent=num(s.shares);$("detailTotalCost").textContent=money(s.totalCost);$("detailMarketValue").textContent=money(s.value);$("detailFavorite").textContent=s.favorite?"★":"☆";$("detailScore").textContent=s.score;$("detailScoreBar").style.width=`${s.score}%`;$("detailAdvice").textContent=s.score>=82?"評分偏強，可續抱並觀察合理加碼點。":s.score>=65?"評分中性，先續抱觀察，不追價。":"評分偏弱，應檢查基本面、趨勢與停損條件。";$("detailReason").value=s.reason||"";$("detailRisk").value=s.risk||"";
const ts=state.trades.filter(x=>x.symbol===s.symbol).sort((a,b)=>a.date.localeCompare(b.date));$("detailTradeList").innerHTML=ts.length?`<div class="trade-row header"><span>成交日</span><span>價格</span><span>數量</span><span>損益／備註</span></div>`+ts.map(t=>`<div class="trade-row"><strong>${esc(t.date.replaceAll("-","/"))}</strong><strong>${num(t.price)}</strong><strong>${num(t.shares)}</strong><strong class="${t.type==="sell"?cls(t.realized):"flat"}">${t.type==="sell"?money(t.realized):esc(t.note||"買進")}</strong></div>`).join(""):'<div class="empty">尚無逐筆交易紀錄</div>';
const buys=ts.filter(x=>x.type==="buy"),maxShares=Math.max(1,...buys.map(x=>x.shares));$("costDistribution").innerHTML=buys.length?buys.map(t=>`<div class="cost-row"><strong>${num(t.price)}</strong><div class="cost-track"><div class="cost-bar" style="width:${t.shares/maxShares*100}%"></div></div><span>${num(t.shares)}股</span></div>`).join(""):'<div class="empty">尚無買進資料</div>';
const ds=state.dividends.filter(x=>x.symbol===s.symbol).sort((a,b)=>b.date.localeCompare(a.date));$("detailDividendTotal").textContent=money(ds.reduce((a,x)=>a+x.amount,0));$("detailDividendCount").textContent=ds.length;$("detailDividendList").innerHTML=ds.length?ds.map(d=>`<div class="mini-row"><span>${esc(d.date)}｜${esc(d.note||"股息")}</span><strong>${money(d.amount)}</strong></div>`).join(""):'<div class="empty">尚無股息紀錄</div>'}
$("detailFavorite").onclick=()=>{const s=state.stocks.find(x=>x.id===currentDetailId);if(s){s.favorite=!s.favorite;save()}};
$("saveDetailNotes").onclick=()=>{const s=state.stocks.find(x=>x.id===currentDetailId);if(s){s.reason=$("detailReason").value.trim();s.risk=$("detailRisk").value.trim();save();toast("投資筆記已儲存")}};

function openStock(s=null){$("dialogTitle").textContent=s?"修改持股":"新增持股";$("stockId").value=s?.id||"";$("symbol").value=s?.symbol||"";$("name").value=s?.name||"";$("category").value=s?.category||"ETF";$("shares").value=s?.shares??"";$("cost").value=s?.cost??"";$("price").value=s?.price??0;$("dayChange").value=s?.dayChange??0;$("stockDialog").showModal()}
$("addBtn").onclick=()=>openStock();$("closeStockDialog").onclick=()=>$("stockDialog").close();
$("stockForm").onsubmit=e=>{e.preventDefault();const id=$("stockId").value,old=state.stocks.find(x=>x.id===id),item={id:id||uid(),symbol:$("symbol").value.trim().toUpperCase(),name:$("name").value.trim(),category:$("category").value,shares:Number($("shares").value),cost:Number($("cost").value),price:Number($("price").value||0),dayChange:Number($("dayChange").value||0),favorite:old?.favorite||false,reason:old?.reason||"",risk:old?.risk||""};state.stocks=id?state.stocks.map(x=>x.id===id?item:x):[...state.stocks,item];$("stockDialog").close();save();toast("持股已儲存")};

function openTrade(prefill=false){$("tradeForm").reset();$("tradeDate").value=new Date().toISOString().slice(0,10);$("tradeFee").value=0;if(prefill&&currentDetailId){const s=state.stocks.find(x=>x.id===currentDetailId);$("tradeSymbol").value=s.symbol;$("tradeName").value=s.name;$("tradeCategory").value=s.category}$("tradeDialog").showModal()}
$("addTradeBtn").onclick=()=>openTrade(false);$("detailAddTrade").onclick=()=>openTrade(true);$("closeTradeDialog").onclick=()=>$("tradeDialog").close();
$("tradeForm").onsubmit=e=>{e.preventDefault();const t={id:uid(),date:$("tradeDate").value,symbol:$("tradeSymbol").value.trim().toUpperCase(),name:$("tradeName").value.trim(),category:$("tradeCategory").value,type:$("tradeType").value,shares:Number($("tradeShares").value),price:Number($("tradePrice").value),fee:Number($("tradeFee").value||0),note:$("tradeNote").value.trim(),realized:0};let h=state.stocks.find(x=>x.symbol===t.symbol);if(t.type==="buy"){if(!h){h={id:uid(),symbol:t.symbol,name:t.name,category:t.category,shares:0,cost:0,price:t.price,dayChange:0,favorite:false,reason:"",risk:""};state.stocks.push(h)}const old=h.shares*h.cost,newc=t.shares*t.price+t.fee;h.cost=(old+newc)/(h.shares+t.shares);h.shares+=t.shares;h.price=t.price}else{if(!h||h.shares<t.shares){toast("持股不足");return}t.realized=(t.price-h.cost)*t.shares-t.fee;h.shares-=t.shares;h.price=t.price;if(h.shares===0)state.stocks=state.stocks.filter(x=>x.id!==h.id)}state.trades.push(t);$("tradeDialog").close();save();toast("交易已儲存")};

function openDividend(prefill=false){$("dividendForm").reset();$("dividendDate").value=new Date().toISOString().slice(0,10);if(prefill&&currentDetailId){const s=state.stocks.find(x=>x.id===currentDetailId);$("dividendSymbol").value=s.symbol;$("dividendName").value=s.name}$("dividendDialog").showModal()}
$("addDividendBtn").onclick=()=>openDividend(false);$("detailAddDividend").onclick=()=>openDividend(true);$("closeDividendDialog").onclick=()=>$("dividendDialog").close();
$("dividendForm").onsubmit=e=>{e.preventDefault();state.dividends.push({id:uid(),date:$("dividendDate").value,symbol:$("dividendSymbol").value.trim().toUpperCase(),name:$("dividendName").value.trim(),amount:Number($("dividendAmount").value),note:$("dividendNote").value.trim()});$("dividendDialog").close();save();toast("股息已儲存")};

function renderTrades(){const list=[...state.trades].sort((a,b)=>b.date.localeCompare(a.date));$("tradeList").innerHTML=list.length?list.map(t=>`<article class="timeline-card"><div class="timeline-head"><div><strong>${esc(t.symbol)}｜${esc(t.name||"")}</strong><div class="stock-name">${t.type==="buy"?"買進":"賣出"}｜${esc(t.date)}</div></div><strong class="${t.type==="sell"?cls(t.realized):""}">${t.type==="sell"?money(t.realized):money(t.shares*t.price+t.fee)}</strong></div><div class="timeline-meta"><div><span>股數</span><strong>${num(t.shares)}</strong></div><div><span>價格</span><strong>${num(t.price)}</strong></div><div><span>手續費</span><strong>${money(t.fee)}</strong></div><div><span>備註</span><strong>${esc(t.note||"—")}</strong></div></div></article>`).join(""):'<div class="empty">尚無交易紀錄</div>'}
function renderDividends(){const list=[...state.dividends].sort((a,b)=>b.date.localeCompare(a.date));$("dividendList").innerHTML=list.length?list.map(d=>`<article class="timeline-card"><div class="timeline-head"><div><strong>${esc(d.symbol)}｜${esc(d.name||"")}</strong><div class="stock-name">${esc(d.date)}｜${esc(d.note||"股息")}</div></div><strong>${money(d.amount)}</strong></div></article>`).join(""):'<div class="empty">尚無股息紀錄</div>'}

$("analyzeImportBtn").onclick=()=>{pending=$("bulkText").value.split(/\r?\n/).map(x=>x.trim()).filter(Boolean).map(line=>{const c=line.split(/\t|,/).map(x=>x.trim());return{symbol:(c[0]||"").toUpperCase(),name:c[1]||"",category:c[2]||"其他",shares:Number(c[3]),cost:Number(c[4]),price:Number(c[5]||0),dayChange:Number(c[6]||0)}});renderPreview();toast(`已分析 ${pending.length} 筆`)};
function renderPreview(){$("importPreview").innerHTML=pending.length?pending.map(x=>`<div class="preview-item"><strong>${esc(x.symbol)}｜${esc(x.name)}</strong><div class="stock-name">${esc(x.category)}｜${num(x.shares)} 股｜均價 ${num(x.cost)}｜現價 ${num(x.price)}</div></div>`).join(""):'<div class="empty">尚無預覽資料</div>'}
$("approveImportBtn").onclick=()=>{for(const x of pending){if(!x.symbol||!Number.isFinite(x.shares)||!Number.isFinite(x.cost))continue;const old=state.stocks.find(s=>s.symbol===x.symbol),item={id:old?.id||uid(),...x,favorite:old?.favorite||false,reason:old?.reason||"",risk:old?.risk||""};if(old)Object.assign(old,item);else state.stocks.push(item)}pending=[];$("bulkText").value="";save();toast("匯入完成")};

document.querySelectorAll(".segment[data-category]").forEach(c=>c.onclick=()=>{document.querySelectorAll(".segment[data-category]").forEach(x=>x.classList.remove("active"));c.classList.add("active");currentCategory=c.dataset.category;render()});
$("searchInput").oninput=e=>{currentSearch=e.target.value.trim().toLowerCase();render()};$("sortSelect").onchange=e=>{currentSort=e.target.value;render()};
$("refreshBtn").onclick=async()=>{if(!state.stocks.length){toast("目前沒有持股");return}const b=$("refreshBtn");b.disabled=true;b.textContent="…";let ok=0;for(const s of state.stocks){for(const m of["tse","otc"]){try{const r=await fetch(`https://mis.twse.com.tw/stock/api/getStockInfo.jsp?ex_ch=${m}_${s.symbol}.tw`,{cache:"no-store"});const j=await r.json(),row=j?.msgArray?.[0];if(row){const p=Number(row.z||row.y);if(p>0){s.price=p;s.name=s.name||row.n;ok++;break}}}catch{}}}save();b.disabled=false;b.textContent="↻";toast(`已更新 ${ok} 檔`)};

function download(content,name,type){const a=document.createElement("a"),blob=new Blob(["\ufeff"+content],{type});a.href=URL.createObjectURL(blob);a.download=name;a.click();URL.revokeObjectURL(a.href)}
$("exportBtn").onclick=()=>download(JSON.stringify({version:"3.0",...state,exportedAt:new Date().toISOString()},null,2),`alpha-one-${new Date().toISOString().slice(0,10)}.json`,"application/json");
$("exportCsvBtn").onclick=()=>download(["股票代號,股票名稱,分類,股數,平均成本,目前價格,今日漲跌幅",...state.stocks.map(s=>[s.symbol,s.name,s.category,s.shares,s.cost,s.price,s.dayChange].join(","))].join("\n"),"alpha-one-holdings.csv","text/csv");
$("importBtn").onclick=()=>$("importFile").click();$("importFile").onchange=async e=>{try{state=normalize(JSON.parse(await e.target.files[0].text()));save();toast("匯入完成")}catch{toast("備份格式錯誤")}e.target.value=""};
$("sampleBtn").onclick=()=>{state={stocks:[{id:uid(),symbol:"00400A",name:"主動國泰動能高息",category:"ETF",shares:3000,cost:13.50,price:13.41,dayChange:-.59,favorite:true,reason:"作為主動式高股息 ETF 部位，分批建立。",risk:"跌破 12.8 或策略失效時重新評估。"}],trades:[{id:uid(),date:"2026-05-14",symbol:"00400A",name:"主動國泰動能高息",category:"ETF",type:"buy",shares:1000,price:13.91,fee:0,note:"首次建立部位",realized:0},{id:uid(),date:"2026-05-15",symbol:"00400A",name:"主動國泰動能高息",category:"ETF",type:"buy",shares:1000,price:13.50,fee:0,note:"第二次加碼",realized:0},{id:uid(),date:"2026-05-19",symbol:"00400A",name:"主動國泰動能高息",category:"ETF",type:"buy",shares:500,price:12.78,fee:0,note:"逢低加碼",realized:0},{id:uid(),date:"2026-07-17",symbol:"00400A",name:"主動國泰動能高息",category:"ETF",type:"buy",shares:500,price:13.31,fee:0,note:"分批加碼",realized:0}],history:[],dividends:[]};save();toast("示範資料已載入")};
$("clearBtn").onclick=()=>{if(confirm("確定清空全部資料？")){state={stocks:[],trades:[],history:[],dividends:[]};save()}};
render();