let portfolio=AlphaStorage.load();
const dom={form:document.getElementById("stockForm"),symbol:document.getElementById("symbolInput"),shares:document.getElementById("sharesInput"),cost:document.getElementById("costInput"),price:document.getElementById("priceInput"),refresh:document.getElementById("refreshBtn"),exportBtn:document.getElementById("exportBtn"),importBtn:document.getElementById("importBtn"),importFile:document.getElementById("importFile"),clearBtn:document.getElementById("clearBtn"),status:document.getElementById("status"),body:document.getElementById("portfolioBody"),table:document.getElementById("portfolioTable"),empty:document.getElementById("emptyState"),count:document.getElementById("stockCount"),totalCost:document.getElementById("totalCost"),totalValue:document.getElementById("totalValue"),totalPnl:document.getElementById("totalPnl"),totalRoi:document.getElementById("totalRoi")};
function money(value){return"NT$"+Math.round(value||0).toLocaleString("zh-TW")}function pct(value){return Number.isFinite(value)?`${value.toFixed(2)}%`:"0.00%"}function cssGain(value){return value>=0?"green":"red"}function saveAndRender(){AlphaStorage.save(portfolio);render()}
function render(){dom.body.innerHTML="";let totalCost=0,totalValue=0;portfolio.forEach((stock,index)=>{const shares=Number(stock.shares)||0,cost=Number(stock.cost)||0,price=Number(stock.price)||0,costAmount=shares*cost,valueAmount=shares*price,pnl=valueAmount-costAmount,roi=costAmount?pnl/costAmount*100:0;totalCost+=costAmount;totalValue+=valueAmount;const row=document.createElement("tr");row.innerHTML=`<td><strong>${stock.symbol}</strong></td><td><input class="inline-input" type="number" value="${shares}" data-index="${index}" data-field="shares"></td><td><input class="inline-input" type="number" step="0.01" value="${cost}" data-index="${index}" data-field="cost"></td><td><input class="inline-input" type="number" step="0.01" value="${price}" data-index="${index}" data-field="price"></td><td>${money(costAmount)}</td><td>${money(valueAmount)}</td><td class="${cssGain(pnl)}">${money(pnl)}</td><td class="${cssGain(roi)}">${pct(roi)}</td><td>${stock.updatedAt||"-"}</td><td><button class="danger-btn delete-row" data-delete="${index}">刪除</button></td>`;dom.body.appendChild(row)});const totalPnl=totalValue-totalCost,totalRoi=totalCost?totalPnl/totalCost*100:0;dom.totalCost.textContent=money(totalCost);dom.totalValue.textContent=money(totalValue);dom.totalPnl.textContent=money(totalPnl);dom.totalPnl.className=cssGain(totalPnl);dom.totalRoi.textContent=pct(totalRoi);dom.totalRoi.className=cssGain(totalRoi);dom.count.textContent=`${portfolio.length} 檔`;dom.table.hidden=portfolio.length===0;dom.empty.style.display=portfolio.length?"none":"block"}
dom.form.addEventListener("submit",event=>{event.preventDefault();portfolio.push({symbol:dom.symbol.value.trim(),shares:Number(dom.shares.value)||0,cost:Number(dom.cost.value)||0,price:Number(dom.price.value)||0,updatedAt:""});dom.form.reset();dom.price.value=0;dom.symbol.focus();saveAndRender()});
dom.body.addEventListener("change",event=>{const input=event.target;const index=Number(input.dataset.index);const field=input.dataset.field;if(!Number.isInteger(index)||!field)return;portfolio[index][field]=Number(input.value)||0;saveAndRender()});
dom.body.addEventListener("click",event=>{const button=event.target.closest("[data-delete]");if(!button)return;const index=Number(button.dataset.delete);portfolio.splice(index,1);saveAndRender()});
dom.refresh.addEventListener("click",async()=>{if(!portfolio.length){dom.status.textContent="沒有持股可以更新。";return}dom.refresh.disabled=true;dom.status.textContent="更新中……";let updated=0;const failed=[];for(const stock of portfolio){try{const result=await AlphaMarket.fetchTwPrice(stock.symbol);stock.price=result.price;stock.updatedAt=result.time||new Date().toLocaleString("zh-TW");updated+=1}catch{failed.push(stock.symbol)}await new Promise(resolve=>setTimeout(resolve,250))}AlphaStorage.save(portfolio);render();dom.status.textContent=`已更新 ${updated} 檔`+(failed.length?`；失敗：${failed.join("、")}`:"");dom.refresh.disabled=false});
dom.exportBtn.addEventListener("click",()=>{const blob=new Blob([JSON.stringify(portfolio,null,2)],{type:"application/json"});const url=URL.createObjectURL(blob);const link=document.createElement("a");link.href=url;link.download="alpha-one-backup.json";link.click();URL.revokeObjectURL(url)});
dom.importBtn.addEventListener("click",()=>dom.importFile.click());
dom.importFile.addEventListener("change",event=>{const file=event.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const data=JSON.parse(reader.result);if(!Array.isArray(data))throw new Error("not array");portfolio=data;saveAndRender();dom.status.textContent="匯入完成。"}catch{alert("匯入失敗，檔案格式不正確。")}};reader.readAsText(file)});
dom.clearBtn.addEventListener("click",()=>{if(!confirm("確定清空所有持股？"))return;portfolio=[];AlphaStorage.clear();render()});
render();
